<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit95da3b82e22139234859d2c309b4705a
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Automattic\\WooCommerce\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Automattic\\WooCommerce\\' => 
        array (
            0 => __DIR__ . '/..' . '/automattic/woocommerce/src/WooCommerce',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Parsedown' => 
            array (
                0 => __DIR__ . '/..' . '/erusev/parsedown',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit95da3b82e22139234859d2c309b4705a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit95da3b82e22139234859d2c309b4705a::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit95da3b82e22139234859d2c309b4705a::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit95da3b82e22139234859d2c309b4705a::$classMap;

        }, null, ClassLoader::class);
    }
}
